SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS CURSAN;
DROP TABLE IF EXISTS HACEN;
DROP TABLE IF EXISTS REALIZAN;
DROP TABLE IF EXISTS ALUMNOS;
DROP TABLE IF EXISTS IMPARTEN;
DROP TABLE IF EXISTS ASIGNATURAS;
DROP TABLE IF EXISTS ELABORAN;
DROP TABLE IF EXISTS EXAMENES;
DROP TABLE IF EXISTS PRACTICAS;
DROP TABLE IF EXISTS PROFESORES;




/* Create Tables */

CREATE TABLE ALUMNOS
(
	NUM_ALU int NOT NULL,
	NOMBRE varchar(20),
	GRUPO varchar(20),
	PRIMARY KEY (NUM_ALU)
);


CREATE TABLE ASIGNATURAS
(
	NUM_ASI int NOT NULL,
	NOMBRE varchar(20),
	PRIMARY KEY (NUM_ASI)
);


CREATE TABLE CURSAN
(
	TRIMESTRE int NOT NULL,
	NUM_ALU int NOT NULL,
	NUM_ASI int NOT NULL
);


CREATE TABLE ELABORAN
(
	FECHA date,
	COD_PRACTICA int NOT NULL,
	NUM_PROF int NOT NULL
);


CREATE TABLE EXAMENES
(
	NUM_EXA int NOT NULL,
	N_PREGUNTAS int,
	FECHA date,
	PRIMARY KEY (NUM_EXA)
);


CREATE TABLE HACEN
(
	NOTA int,
	NUM_ALU int NOT NULL,
	NUM_EXA int NOT NULL
);


CREATE TABLE IMPARTEN
(
	NUM_ASI int NOT NULL,
	NUM_PROF int NOT NULL
);


CREATE TABLE PRACTICAS
(
	COD_PRACTICA int NOT NULL,
	TITULO varchar(20),
	NIVEL varchar(20),
	PRIMARY KEY (COD_PRACTICA)
);


CREATE TABLE PROFESORES
(
	NUM_PROF int NOT NULL,
	NOMBRE varchar(20),
	PRIMARY KEY (NUM_PROF)
);


CREATE TABLE REALIZAN
(
	NOTA int,
	FECHA date,
	NUM_ALU int NOT NULL,
	COD_PRACTICA int NOT NULL
);



/* Create Foreign Keys */

ALTER TABLE CURSAN
	ADD FOREIGN KEY (NUM_ALU)
	REFERENCES ALUMNOS (NUM_ALU)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HACEN
	ADD FOREIGN KEY (NUM_ALU)
	REFERENCES ALUMNOS (NUM_ALU)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE REALIZAN
	ADD FOREIGN KEY (NUM_ALU)
	REFERENCES ALUMNOS (NUM_ALU)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CURSAN
	ADD FOREIGN KEY (NUM_ASI)
	REFERENCES ASIGNATURAS (NUM_ASI)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE IMPARTEN
	ADD FOREIGN KEY (NUM_ASI)
	REFERENCES ASIGNATURAS (NUM_ASI)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HACEN
	ADD FOREIGN KEY (NUM_EXA)
	REFERENCES EXAMENES (NUM_EXA)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ELABORAN
	ADD FOREIGN KEY (COD_PRACTICA)
	REFERENCES PRACTICAS (COD_PRACTICA)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE REALIZAN
	ADD FOREIGN KEY (COD_PRACTICA)
	REFERENCES PRACTICAS (COD_PRACTICA)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ELABORAN
	ADD FOREIGN KEY (NUM_PROF)
	REFERENCES PROFESORES (NUM_PROF)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE IMPARTEN
	ADD FOREIGN KEY (NUM_PROF)
	REFERENCES PROFESORES (NUM_PROF)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



